CREATE DATABASE Acceloka
GO

USE Acceloka
GO

CREATE TABLE Category(
	CategoryId INT NOT NULL CONSTRAINT PK_Category PRIMARY KEY IDENTITY (1,1),
	CategoryName VARCHAR(255) NOT NULL
)

CREATE TABLE Tickets(
	Id Int Primary Key IDENTITY(1,1),
	CategoryId INT NOT NULL CONSTRAINT FK_Tickets_Category FOREIGN KEY REFERENCES Category(CategoryId) ON DELETE CASCADE,
	TicketCode VARCHAR(50) NOT NULL UNIQUE,
	TicketName VARCHAR(255) NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	EventDate DATETIME2 NOT NULL,
	Quota INT NOT NULL,
)

CREATE TABLE BookedTicket(
	Id INT PRIMARY KEY IDENTITY(1,1),
	BookedTicketId UNIQUEIDENTIFIER NOT NULL,
	TicketCode VARCHAR(50) NOT NULL CONSTRAINT FK_BookedTicket_Tickets FOREIGN KEY REFERENCES Tickets(TicketCode) ON DELETE CASCADE,
	Quantity INT NOT NULL
)